from enum import Enum


class Category(Enum):
    FILM_ANIMATION = 1
    AUTOS_VEHICLES = 2
    MUSIC = 10
    PETS_ANIMALS = 15
    SPORTS = 17
    SHORT_MOVIES = 18
    TRAVEL_EVENTS = 19
    GAMING = 20
    VIDEOBLOGGING = 21
    PEOPLE_BLOGS = 22
    COMEDY = 23
    ENTERTAINMENT = 24
    NEWS_POLITICS = 25
    HOWTO_STYLE = 26
    EDUCATION = 27
    SCIENCE_TECHNOLOGY = 28
    NONPROFITS_ACTIVISM = 29
    MOVIES = 30
    ANIME_ANIMATION = 31
    ACTION_ADVENTURE = 32
    CLASSICS = 33
    DOCUMENTARY = 35
    DRAMA = 36
    FAMILY = 37
    FOREIGN = 38
    HORROR = 39
    SCIFI_FANTASY = 40
    THRILLER = 41
    SHORTS = 42
    SHOWS = 43
    TRAILERS = 44
